export const GET_POST_DETAIL_REQUESTED = 'GET_POST_DETAIL_REQUESTED';
export const GET_POST_DETAIL_SUCCEEDED = 'GET_POST_DETAIL_SUCCEEDED';
export const GET_POST_DETAIL_FAILED = 'GET_POST_DETAIL_FAILED';

export default {
    GET_POST_DETAIL_REQUESTED,
    GET_POST_DETAIL_SUCCEEDED,
    GET_POST_DETAIL_FAILED
}
